alienspider-black:
  drops:
    drop1:
      command: "give %player% diamond 1"
      chance: 0.5
      message: "&b&lYou got a diamond sword" # custom message supporting color codes
    drop2:
      command: "give %player% iron_sword 1"
      chance: 0.3
      message: "&e&lYou got an iron sword" # custom message supporting color codes
    drop3:
      command: "money give %player% 100"
      chance: 0.2
      message: "&a&lYou got 100 money" # custom message supporting color codes

custom_zombie:
  drops:
    drop1:
      command: "give %player% gold_ingot 1"
      chance: 0.3
      message: "&6&lYou got a gold ingot" # custom message supporting color codes
    drop2:
      command: "give %player% iron_sword 1"
      chance: 0.2
      message: "&7&lYou got an iron sword" # custom message supporting color codes
    drop3:
      command: "give %player% diamond_sword 1"
      chance: 0.1
      message: "&b&lYou got a diamond sword" # custom message supporting color codes

another_custom_mob:
  drops:
    drop1:
      command: "iagive %player% potion_of_regeneration 1"
      chance: 0.2
      message: "&d&lYou got a potion of regeneration" # custom message supporting color codes
    drop2:
      command: "money give %player% 500"
      chance: 0.4
      message: "&a&lYou got 500 money" # custom message supporting color codes
