name: MythicDrop
<<<<<<< HEAD
version: '2.0-SNAPSHOT'
main: fr.elias.mythicDrop.MythicDrop
api-version: '1.21'
=======
version: 1.0.0
author: Elias
main: me.afelia.mythicdrop.MythicDrop
api-version: '1.20'
load: STARTUP
>>>>>>> b74e8ff307efcf592f905cc1ffc8c6c41c21e67c
